language: generic
sudo: required
services:
- docker
os:
- linux
env:
  matrix:
  - CONDA_PY=27
  - CONDA_PY=35
  - CONDA_PY=36
  global:
    secure: YvZ8bn4U/x5GvGeyjQNojOfahbYtes7h+bevu5eauil0OJ+1NsFxpZeO761LUubIUxESrmcRZaUp7NB/IOiRvUmFEXChu9mIEOrGVJgMLbnc+pC4eoRtr3+54kiiuBo2wL411dtpDYVrtUJHc70n4OVnhA5jdOvrwx9VurcXM4Oj0xoSgl3lDZnxCYvb4c4rl4qOC+J72+5IWuRkki0s0UKE32Ufj8XfPuES1qGv5feCGKj25cAWBkDtYFQosZ5fNWr3I69lAD4GTmZ/knHXyswkMTyYdyV1gj30GAnAiG77Mr6qaedbzGQWz3cNCCZ2QasgAXY8zpRLaD5FRQrmbzM0DwVfReolWwApJBrGqMkzg0BAJDvtCXrL0nArh7WKrQm7PacCgS6vkmHwqz7IUKEdZU7skNApwaTgGcmt3qs0OfR4RjrmoolSoHN/yYFT6HoX2gWDVWcaNsAxhS0nSuggZ1AacpHOVspgyCLoi51vJFGxnmyFvbniJo/6T1tfY3wV0MaapNyM2vlBLGNpQCMNpLqgquHPn15wfZlj/l8zTtv50csgodQ8tlxLP+pFtCx36zoKJ0Q8l11UQXUQNUDgLCZrDvXX3aoRS8UBXCPmu0CA8QMp/lrogy95a5aM8rkKF5+YYjLdeczhZKcHYHhlJ9OH26nGiVG9cDo2+tU=
before_script:
- |
  echo "Stopping Travis-CI's PostgreSQL service."
  sudo service postgresql stop
install:
- |
  sudo apt-get update
  echo "Installing a fresh version of Miniconda."
  MINICONDA_URL="https://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-$(case $TRAVIS_OS_NAME in (linux) echo Linux;; (osx) echo MacOSX;;esac)-x86_64.sh"
  curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
- |
  echo "Configuring conda."
  source $HOME/miniconda3/bin/activate root
  conda install -y conda-build anaconda-client
script:
- conda build -c conda-forge -c "https://conda.anaconda.org/t/$ANACONDA_TOKEN/intake"
  ./conda
- if [[ -n "${TRAVIS_TAG}" ]]; then anaconda -t ${ANACONDA_TOKEN} upload `conda build
  -c intake/label/main --output ./conda`; fi
notifications:
  email: false
  on_success: change
  on_failure: always
